import React from "react";
import DefaultLayout from "../components/layout/DefaultLayout";
import ClearFix from "../components/common/ClearFix";

const ProductCollectionPage = () => {
    return <DefaultLayout fixedHeader>
        <ClearFix />
        <div>Product Collection Page</div>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio minus consequuntur modi deleniti alias ipsum nesciunt! Vitae quo molestiae assumenda molestias, velit quod fuga excepturi quis dolorum aspernatur et quos aperiam dolor obcaecati porro, similique iste impedit? Commodi, iste architecto laudantium similique quas, tempora blanditiis mollitia optio libero repellendus sit ullam necessitatibus dignissimos quaerat minus tempore? Quaerat rerum ut, perspiciatis reiciendis cumque earum exercitationem ab tenetur, numquam eaque dolorem aperiam magni itaque, possimus quas delectus expedita molestias amet! Veritatis ullam cumque reprehenderit eos fugit corporis nobis explicabo maiores! Tempora, eveniet qui in nihil atque voluptates fuga unde consequatur, porro repellendus beatae delectus adipisci aspernatur quaerat corporis repellat vitae saepe consectetur maxime doloribus enim dolore. Tempore, quisquam ex cumque itaque nam quis nostrum ad dolorum. Possimus porro quae molestias, nihil iste suscipit libero dicta quo amet. Quasi in placeat eveniet! Vel possimus vero magnam alias fugiat culpa voluptates. Hic, laborum officia?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio minus consequuntur modi deleniti alias ipsum nesciunt! Vitae quo molestiae assumenda molestias, velit quod fuga excepturi quis dolorum aspernatur et quos aperiam dolor obcaecati porro, similique iste impedit? Commodi, iste architecto laudantium similique quas, tempora blanditiis mollitia optio libero repellendus sit ullam necessitatibus dignissimos quaerat minus tempore? Quaerat rerum ut, perspiciatis reiciendis cumque earum exercitationem ab tenetur, numquam eaque dolorem aperiam magni itaque, possimus quas delectus expedita molestias amet! Veritatis ullam cumque reprehenderit eos fugit corporis nobis explicabo maiores! Tempora, eveniet qui in nihil atque voluptates fuga unde consequatur, porro repellendus beatae delectus adipisci aspernatur quaerat corporis repellat vitae saepe consectetur maxime doloribus enim dolore. Tempore, quisquam ex cumque itaque nam quis nostrum ad dolorum. Possimus porro quae molestias, nihil iste suscipit libero dicta quo amet. Quasi in placeat eveniet! Vel possimus vero magnam alias fugiat culpa voluptates. Hic, laborum officia?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio minus consequuntur modi deleniti alias ipsum nesciunt! Vitae quo molestiae assumenda molestias, velit quod fuga excepturi quis dolorum aspernatur et quos aperiam dolor obcaecati porro, similique iste impedit? Commodi, iste architecto laudantium similique quas, tempora blanditiis mollitia optio libero repellendus sit ullam necessitatibus dignissimos quaerat minus tempore? Quaerat rerum ut, perspiciatis reiciendis cumque earum exercitationem ab tenetur, numquam eaque dolorem aperiam magni itaque, possimus quas delectus expedita molestias amet! Veritatis ullam cumque reprehenderit eos fugit corporis nobis explicabo maiores! Tempora, eveniet qui in nihil atque voluptates fuga unde consequatur, porro repellendus beatae delectus adipisci aspernatur quaerat corporis repellat vitae saepe consectetur maxime doloribus enim dolore. Tempore, quisquam ex cumque itaque nam quis nostrum ad dolorum. Possimus porro quae molestias, nihil iste suscipit libero dicta quo amet. Quasi in placeat eveniet! Vel possimus vero magnam alias fugiat culpa voluptates. Hic, laborum officia?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio minus consequuntur modi deleniti alias ipsum nesciunt! Vitae quo molestiae assumenda molestias, velit quod fuga excepturi quis dolorum aspernatur et quos aperiam dolor obcaecati porro, similique iste impedit? Commodi, iste architecto laudantium similique quas, tempora blanditiis mollitia optio libero repellendus sit ullam necessitatibus dignissimos quaerat minus tempore? Quaerat rerum ut, perspiciatis reiciendis cumque earum exercitationem ab tenetur, numquam eaque dolorem aperiam magni itaque, possimus quas delectus expedita molestias amet! Veritatis ullam cumque reprehenderit eos fugit corporis nobis explicabo maiores! Tempora, eveniet qui in nihil atque voluptates fuga unde consequatur, porro repellendus beatae delectus adipisci aspernatur quaerat corporis repellat vitae saepe consectetur maxime doloribus enim dolore. Tempore, quisquam ex cumque itaque nam quis nostrum ad dolorum. Possimus porro quae molestias, nihil iste suscipit libero dicta quo amet. Quasi in placeat eveniet! Vel possimus vero magnam alias fugiat culpa voluptates. Hic, laborum officia?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio minus consequuntur modi deleniti alias ipsum nesciunt! Vitae quo molestiae assumenda molestias, velit quod fuga excepturi quis dolorum aspernatur et quos aperiam dolor obcaecati porro, similique iste impedit? Commodi, iste architecto laudantium similique quas, tempora blanditiis mollitia optio libero repellendus sit ullam necessitatibus dignissimos quaerat minus tempore? Quaerat rerum ut, perspiciatis reiciendis cumque earum exercitationem ab tenetur, numquam eaque dolorem aperiam magni itaque, possimus quas delectus expedita molestias amet! Veritatis ullam cumque reprehenderit eos fugit corporis nobis explicabo maiores! Tempora, eveniet qui in nihil atque voluptates fuga unde consequatur, porro repellendus beatae delectus adipisci aspernatur quaerat corporis repellat vitae saepe consectetur maxime doloribus enim dolore. Tempore, quisquam ex cumque itaque nam quis nostrum ad dolorum. Possimus porro quae molestias, nihil iste suscipit libero dicta quo amet. Quasi in placeat eveniet! Vel possimus vero magnam alias fugiat culpa voluptates. Hic, laborum officia?</p>
        </DefaultLayout>;
}

export default ProductCollectionPage;